### ISSUE TITLE
Is it possible to track rune keeper fire dots and their tier on an enemy?

### ISSUE THREAD

**Issue by NPCRUS** [souruko/Gibberish#3]
- tried effect target
- tried use target entity

**Comment by souruko** [comment]
hi
tracking them is possible with a few different approaches:

not sure what your problems where here but effect target should work (maybe check if track target is active?) but you can for sure track every target effect this way.
the big downside to using effect target is that we can not distinguish between your own and any other rk that is attacking the same target.


so in my opinion there is a better approach: combat chat

while using gibberish i started to use combat chat more and more for timers as it is often the best way to track something between skill/debuff. and every information including the tier of you debuff is in there. dot durations could also be tracked from skill cd but with chat you can make sure the dot is on the target aswell.
obviously this also can have downsides here the main downside is that it does not work if you have a dot on multiple targets as it will confuse itself.

here is an example with tier/duration for writ with combat chat:

> 
> === Gibberish 2.x ===
> 
> === group ===
> name~=rk writ;
> color~=0, 0, 0;
> === group end ===
> 
> === window ===
> name~=duration;
> type~=3;
> id~=145;
> load~=true;
> width~=32;
> height~=32;
> left~=0.1;
> top~=0.1;
> frame~=1;
> spacing~=2;
> number_format~=1;
> frame_color~=0, 0, 0;
> back_color~=255, 255, 255;
> bar_color~=0, 0, 0;
> font_color_1~=255, 255, 255;
> font_color_2~=255, 255, 255;
> opacity~=0.5;
> opacity2~=0.5;
> ascending~=false;
> orientation~=true;
> overlay~=false;
> reset_on_target_change~=false;
> trigger_id~=nil;
> === window end ===
> 
> === trigger ===
> type~=4;
> token~=hit</rgb> with Writ of Fire on;
> description~=;
> custom_timer~=true;
> timer~=21;
> icon~=1091440848;
> id~=365908703.22254;
> text~=;
> text_modifier~=1;
> threshold~=3;
> use_threshold~=true;
> flashing_multi~=2;
> flashing~=true;
> loop~=false;
> reset~=false;
> unique~=true;
> removable~=true;
> use_regex~=true;
> hide_timer~=false;
> sort_index~=1;
> counter_start~=nil;
> 
> === window ===
> name~=tier;
> type~=3;
> id~=146;
> load~=true;
> width~=32;
> height~=32;
> left~=0.1;
> top~=0.1;
> frame~=1;
> spacing~=2;
> number_format~=1;
> frame_color~=0, 0, 0;
> back_color~=255, 255, 255;
> bar_color~=0, 0, 0;
> font_color_1~=255, 255, 255;
> font_color_2~=255, 255, 255;
> opacity~=0;
> opacity2~=0;
> ascending~=false;
> orientation~=true;
> overlay~=false;
> reset_on_target_change~=false;
> trigger_id~=nil;
> === window end ===
> 
> === trigger ===
> type~=4;
> token~=hit</rgb> with Writ of Fire . Tier . on;
> description~=;
> custom_timer~=true;
> timer~=3.1;
> icon~=1091440848;
> id~=365908801.74752;
> text~=;
> text_modifier~=4;
> threshold~=3;
> use_threshold~=true;
> flashing_multi~=2;
> flashing~=true;
> loop~=false;
> reset~=false;
> unique~=true;
> removable~=true;
> use_regex~=true;
> hide_timer~=true;
> sort_index~=1;
> counter_start~=nil;

**Comment by NPCRUS** [comment]
Hi,
thank you for your answer, after this I would be able to use your tool much better.
Therefore, we can close it 👍
